### ISSUE TITLE
What are  Ansible and pyYAML versions for hosts.yml provided as an example?

### ISSUE THREAD

**Issue by youtweakit** [poanetwork/deployment-bridge#1]

**Comment by phahulin** [comment]
Please clarify your question, there is a file containing complete set of parameters https://github.com/poanetwork/deployment-bridge/blob/master/example-hosts.yml also there is an example in README where all of these parameters are set https://github.com/poanetwork/deployment-bridge#deployment-process

**Comment by youtweakit** [comment]
Hello phahulin,
am trying to use ansible versions from 2.0.0 to 2.5.b02
using pip installed ansible with python2.7 onboard and i've got parsing issues, and some ssh issues(but they are because i use local install ansible_connection=local) . Please provide ansible version that play on your instance. Different ansible versions can use different  syntax of variables defining.

**Comment by youtweakit** [comment]
Look's like that: ERROR! Attempted to read "hosts.yml" as YAML: Syntax Error while loading YAML.


The error appears to have been in '/var/opt/deployment-bridge/hosts.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      ### parity configs
      home_chain_json: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/PoA_home.json"
      ^ here
This one looks easy to fix.  It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote.  For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'
Or equivalently:
   when: "'ok' in result.stdout"
Attempted to read "hosts.yml" as ini file: hosts.yml:5: Expected key=value host variable assignment, got: root


Using ansible 2.3.0

**Comment by youtweakit** [comment]
Attempted to read "hosts.yml" as ini file: hosts.yml:5: Expected key=value host variable assignment, got: root

This one corresponds to ansible_user: root -but there is no syntax mistakes to my mind. maybe in later versions of ansible (:) must be (=). So different versions = different syntax issues))) am still trying to find out right working version)

**Comment by phahulin** [comment]
I'm running `ansible 2.4.2.0`, `python 2.7.12`

Could you share your `hosts.yml` in full? There might a syntax error on a line before line 5... as a guess, what did you set on line 4 for ip address instead of `192.0.2.1`? The `Expected key=value` error is most likely caused by ansible trying to interpret hosts.yml as ini file due it's failure to parse it as proper yaml.

Also, I'd recommend running on a virtual machine or remote server, this is still not very much tested and installs some pip packages and 3 services, which might be undesirable on a personal box.

**Comment by youtweakit** [comment]
Let's test together ;-) So with ans 2.4.3 we got this - fatal: [51.15.220.33:]: FAILED! => {
    "failed": true, 
    "msg": "The task includes an option with an undefined variable. The error was: 'home_chain_name' is undefined\n\nThe error appears to have been in '/var/opt/deployment-bridge/roles/parity-home/tasks/main.yml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create folder for parity-home\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'home_chain_name' is undefined"
}
My hosts.yml - 
---
all:
  hosts:
    51.15.220.33: ansible_connection=local

      ### parity configs
      home_chain_json: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/PoA_home.json"
      home_chain_name: "PoA_home"
      home_signer_address: "0x842eb2142c5aa1260954f07aae39ddee1640c3a7"
      home_signer_keyfile: '{"id":"7586acc4-a46d-1a69-5615-13596cceb982","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"d5bf770f4b18845f67bad272a50$
      home_signer_password: "11"

      foreign_chain_json: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/PoA_foreign.json"
      foreign_chain_name: "PoA_foreign"
      foreign_signer_address: "0xf3ee321df87781864f46f6464e764c2827fca73b"
      foreign_signer_keyfile: '{"id":"7f1aae19-e63f-fdab-e917-ca01dbffa25a","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"f568bfdfc7c4346997c55685$
      foreign_signer_password: "11"

      ### bridge config
      initial_deployment: yes
      db_toml_location: ""

      home_required_confirmations: 0
      home_poll_interval: 2
      home_request_timeout: 360

      foreign_required_confirmations: 0
      foreign_poll_interval: 2
      foreign_request_timeout: 360

      authorities:
        - "0xf3ee321df87781864f46f6464e764c2827fca73b"
      required_signatures: 1

      ### tests
      actor_address: "0x37a30534da3d53aa1867adde26e114a3161b2b12"
      actor_keyfile: '{"id":"8437ae14-1e28-75d3-4512-a60d63dbfb64","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"6ac9cafc4afa4ec408c9e72d99d77b7d"$
      actor_password: "11"

**Comment by youtweakit** [comment]
According to this - "msg": "The task includes an option with an undefined variable. The error was: 'home_signer_address' is undefined\n\nThe error appears to have been in '/var/opt/deployment-bridge/roles/parity-home/tasks/main.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Put home signer keyfile in keys folder\n  ^ here\n\nexception type:
I think that parity-home role task doesn't see defined vars from hosts.yml. Isn't it better to put all vars in group_vars: section or to roles tasks directly? i'll fill all necessary fields manualy. For local install on remote server i did this: 
---

### global settings
ssh_root:
    - "{{ lookup('file', './id_rsa.pub') }}"

base_path: "/home/{{ ansible_user }}/poa-bridge"    - in group_vars
And 
- name: Add ssh keys for root
  authorized_key: user=root key={{ item }} state=present exclusive=yes
  with_items: "{{ ssh_root }}"   - in parity-home main.yml

**Comment by phahulin** [comment]
Could you please fix markup, use three "```" to circumvent large code blocks
yaml is very sensitive to spaces, quotes, etc, so it might be important

**Comment by youtweakit** [comment]
`"FileNotFoundError: [Errno 2] No such file or directory: '/home/root/poa-bridge/bridge/db.toml'"`


Seeking db.toml))))

**Comment by phahulin** [comment]
Most likely bridge din't start properly, most likely because either home or foreign parity failed, please check
```
systemctl status bridge
```
most probably failed. Then check parity:
```
systemctl status parity-home
```
if it's active. check the other one
```
systemctl status parity-foreign
```

**Comment by phahulin** [comment]
Find the one that failed then go to `poa-bridge/home` or `poa-bridge/foreign` correspondingly and try to start it manually:
```
./parity --config node.toml
```
copy-paste the error message here

**Comment by youtweakit** [comment]
you're right - parity doesn't work:
```
 bridge.service - bridge
   Loaded: loaded (/etc/systemd/system/bridge.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2018-02-21 21:16:47 UTC; 17min ago
  Process: 6457 ExecStart=/home/root/poa-bridge/bridge/bridge --config /home/root/poa-bridge/bridge/config.toml --database /home/root/poa-bridge/bridge/db.toml (code=ex
 Main PID: 6457 (code=exited, status=0/SUCCESS)

Feb 21 21:16:47 scw-275de3 systemd[1]: bridge.service: Service hold-off time over, scheduling restart.
Feb 21 21:16:47 scw-275de3 systemd[1]: Stopped bridge.
Feb 21 21:16:47 scw-275de3 systemd[1]: bridge.service: Start request repeated too quickly.
Feb 21 21:16:47 scw-275de3 systemd[1]: Failed to start bridge.

root@scw-275de3:/var/opt/deployment-bridge# systemctl status parity-home
● parity-home.service - parity-home
   Loaded: loaded (/etc/systemd/system/parity-home.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Wed 2018-02-21 21:16:32 UTC; 17min ago
  Process: 6080 ExecStart=/home/root/poa-bridge/home/parity --config node.toml (code=exited, status=1/FAILURE)
 Main PID: 6080 (code=exited, status=1/FAILURE)

Feb 21 21:16:32 scw-275de3 systemd[1]: parity-home.service: Unit entered failed state.
Feb 21 21:16:32 scw-275de3 systemd[1]: parity-home.service: Failed with result 'exit-code'.
Feb 21 21:16:32 scw-275de3 systemd[1]: parity-home.service: Service hold-off time over, scheduling restart.
Feb 21 21:16:32 scw-275de3 systemd[1]: Stopped parity-home.
Feb 21 21:16:32 scw-275de3 systemd[1]: parity-home.service: Start request repeated too quickly.
Feb 21 21:16:32 scw-275de3 systemd[1]: Failed to start parity-home.
root@scw-275de3:/var/opt/deployment-bridge# systemctl status parity-foreign
● parity-foreign.service - parity-foreign
   Loaded: loaded (/etc/systemd/system/parity-foreign.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Wed 2018-02-21 21:16:39 UTC; 18min ago
  Process: 6281 ExecStart=/home/root/poa-bridge/foreign/parity --config node.toml (code=exited, status=1/FAILURE)
 Main PID: 6281 (code=exited, status=1/FAILURE)

Feb 21 21:16:39 scw-275de3 systemd[1]: parity-foreign.service: Unit entered failed state.
Feb 21 21:16:39 scw-275de3 systemd[1]: parity-foreign.service: Failed with result 'exit-code'.
Feb 21 21:16:39 scw-275de3 systemd[1]: parity-foreign.service: Service hold-off time over, scheduling restart.
Feb 21 21:16:39 scw-275de3 systemd[1]: Stopped parity-foreign.
Feb 21 21:16:39 scw-275de3 systemd[1]: parity-foreign.service: Start request repeated too quickly.
Feb 21 21:16:39 scw-275de3 systemd[1]: Failed to start parity-foreign.

```
After `chmod +x parity` and manual start - 
`Account 842e…c3a7 not found for the current chain. You can create an account via RPC, UI or `parity account new --chain chain.json --keys-path parity_data/keys`.`

Seems need to create new accounts, and reconfigure all stuff manually...

**Comment by phahulin** [comment]
So none of them started. This account should have been created by the playbook, please do
```
ls /home/root/poa-bridge/foreign/parity_data
ls /home/root/poa-bridge/foreign/parity_data/keys
```
and
```
ls /home/root/poa-bridge/home/parity_data
ls /home/root/poa-bridge/home/parity_data/keys
```

**Comment by youtweakit** [comment]
```
root@scw-275de3:/home/root/poa-bridge/home# ls /home/root/poa-bridge/foreign/parity_data
cache  chains  dapps  keys  signer
root@scw-275de3:/home/root/poa-bridge/home# ls /home/root/poa-bridge/foreign/parity_data/keys
PoA_foreign

```
```
root@scw-275de3:/home/root/poa-bridge/home# ls /home/root/poa-bridge/home/parity_data
cache  chains  dapps  keys  signer
root@scw-275de3:/home/root/poa-bridge/home# ls /home/root/poa-bridge/home/parity_data/keys
PoA_home  PoA_Home
```

**Comment by phahulin** [comment]
OK, not sure about `foreign` at the moment, but there seems to be a case error in `home`: should be PoA_home, not PoA_Home.
please double check values in hosts.yml for `home_chain_name` and `foreign_chain_name`.
I'd recommend you delete `poa-bridge` folder and run playbook again. Services are down anyway, so no need to stop them.

**Comment by youtweakit** [comment]
all the same error in token_foreign.py  but fixed PoA_home(...
maybe we can turn ignore_errors to yes? in ExecStart?

**Comment by youtweakit** [comment]
> please double check values in hosts.yml for home_chain_name and foreign_chain_name

YAML doesn't parse hosts.yml in my case. )))

**Comment by phahulin** [comment]
How did you make it run then?

**Comment by youtweakit** [comment]
Following playbook structure work's for Scaleway hosting instance. (pip installed ansible 2.4.2.0)
file hosts.yml
`51.15.220.33 ansible_connection=local`
file `all.yml` in `group_vars` folder 
```
---

ansible_user: root

### parity configs
      home_chain_json: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/PoA_home.json"
      home_chain_name: "PoA_home"
      home_signer_address: "0x842eb2142c5aa1260954f07aae39ddee1640c3a7"
      home_signer_keyfile: '{"id":"7586acc4-a46d-1a69-5615-13596cceb982","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"d5bf770f4b18845f67bad272a50720ad"},"ciphertext":"e97c949c28f0e30778359d7ad4ebf023b10a8bd20b023a0dbdae99a89159f96b","kdf":"pbkdf2","kdfparams":{"c":10240,"dklen":32,"prf":"hmac-sha256","salt":"c61d0e8e2d8c74a676eaf32745eb54db0cf75f973d2e2364121fca32a144a605"},"mac":"a61278fdcbcabc19c90fb52a5022bb246024f4ff1660cf961135af51da1b5296"},"address":"842eb2142c5aa1260954f07aae39ddee1640c3a7","name":"","meta":"{}"}'
      home_signer_password: "11"

      foreign_chain_json: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/PoA_foreign.json"
      foreign_chain_name: "PoA_foreign"
      foreign_signer_address: "0xf3ee321df87781864f46f6464e764c2827fca73b"
      foreign_signer_keyfile: '{"id":"7f1aae19-e63f-fdab-e917-ca01dbffa25a","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"f568bfdfc7c4346997c55685b97856bd"},"ciphertext":"a253fb25e484551fa90e50c503cf2b288082e6138efc39d9b95214f2e6b451dd","kdf":"pbkdf2","kdfparams":{"c":10240,"dklen":32,"prf":"hmac-sha256","salt":"8c884d52dd3d573716938a0c0db95a2a89aad77e6c13f82a0bb1e36c72860c9c"},"mac":"fea53c70a3a265a7b618a5839cd51affce4120781cda6a7011ade73b8bb34c45"},"address":"f3ee321df87781864f46f6464e764c2827fca73b","name":"","meta":"{}"}'
      foreign_signer_password: "11"

      ### bridge config
      initial_deployment: yes
      db_toml_location: ""

      home_required_confirmations: 0
      home_poll_interval: 2
      home_request_timeout: 360

      foreign_required_confirmations: 0
      foreign_poll_interval: 2
      foreign_request_timeout: 360

      authorities:
        - "0xf3ee321df87781864f46f6464e764c2827fca73b"
      required_signatures: 1

      ### tests
      actor_address: "0x37a30534da3d53aa1867adde26e114a3161b2b12"
      actor_keyfile: '{"id":"8437ae14-1e28-75d3-4512-a60d63dbfb64","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"6ac9cafc4afa4ec408c9e72d99d77b7d"},"ciphertext":"d4c72972233cadf95e3fda4598692cb08461807ebcfa153dc123b48de438bbdb","kdf":"pbkdf2","kdfparams":{"c":10240,"dklen":32,"prf":"hmac-sha256","salt":"c1fa041558f35b0ff17aa1e0ab49b71ecceff739a2f6f87d7abc8eb0661df3c5"},"mac":"d968ac0bad6361192c4ab1c2f96fade3eab05de3c7edd7dfb86b686de2a6429c"},"address":"37a30534da3d53aa1867adde26e114a3161b2b12","name":"","meta":"{}"}'
### global settings
base_path: "/home/{{ ansible_user }}/poa-bridge"

### parity service
parity_bin_url: "https://d1h4xl4cr1h0mo.cloudfront.net/v1.9.2/x86_64-unknown-linux-gnu/parity"
parity_bin_sha256: "3604a030388cd2c22ebe687787413522106c697610426e09b3c5da4fe70bbd33"

### parity home side configs
home_name: "home"

### parity foreign side configs
foreign_name: "foreign"

### bridge service
bridge_bin_url: "https://transfer.sh/ocdh7/bridge"
bridge_bin_sha256: "3bb5b107159581ebff00d7cb62a01df71785d9cf87c5a9e176e75995921b3850"

### bridge config
bridge_contract_source: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/bridge/contracts/bridge.sol"
token_contract_source: "https://raw.githubusercontent.com/poanetwork/parity-bridge-research/master/erc20/bridge/token/BridgeableToken.sol"

estimated_gas_cost_of_withdraw: 0

home_contract_name: "HomeBridge"
foreign_contract_name: "ForeignBridge"

home_deploy_gas: 3000000
home_deploy_gas_price: 18000000000
foreign_deploy_gas: 3000000
foreign_gas_price: 18000000000
deposit_relay_gas: 1200000
deposit_repay_gas_price: 18000000000
withdraw_confirm_gas: 3000000
withdraw_gas_price: 18000000000
withdraw_relay_gas: 3000000
withdraw_relay_gas_price: 18000000000

### initial deployment
solc_bin_url: "https://github.com/ethereum/solidity/releases/download/v0.4.20/solc-static-linux"
solc_bin_sha256: "d966b8215a4f83377ce9d622c9198fe91e5b93300652bf081aaf2f6aa3ac6a16" #
```
There is very important to install Rust(execute this - `curl https://sh.rustup.rs -sSf | sh`). Am trying to add task to initial deployment playbook like
```
- name: Install RustUp
 become_user: root
shell: 'curl https://sh.rustup.rs -sSf | sh'
```
but it needs non interative mode. How can i get in non interactive mode during sh installation?
