### ISSUE TITLE
One account should be used for home and foreign networks

### ISSUE THREAD

**Issue by akolotov** [poanetwork/deployment-bridge#17]
As per discussion with the team which is doing security audit of the bridge we decided to have one account to sign transactions in home and foreign network.
Consider to change deployment scripts as so their work with config:
```
hosts:
    192.0.2.1:
      ansible_user: ubuntu
      ansible_python_interpreter: "/usr/bin/python3"
      validator_address: ""
      validator_keyfile: ''
      validator_password: ""
      syslog_server_port: ""        # only if you want to forward syslog to a special server. format should be server:port
 ```

Where `validator_address`, `validator_keyfile` and `validator_password` will be applied to the bridge configuration file for `[home]` and `[foreign]`.
