### ISSUE TITLE
account error InvalidAccount

### ISSUE THREAD

**Issue by marekkirejczyk** [poanetwork/deployment-bridge#28]
I try to setup test instance of parity bridge locally. I get the following error:
`account error InvalidAccount`

I am using following commands:

Home network:
```sh
parity --chain dev --port 30304 --unlock 0x00...72 --password home_password.txt
```

Foreign for networks:
```sh
parity --chain kovan --pruning=fast --jsonrpc-port 9545 --no-ws --ui-port=8181 --unlock 0x00...cE --password foreign_password.txt
```
Bridge:
```sh
bridge --config config.toml --database db.toml --allow-insecure-rpc-endpoints
```

Content of config.toml
```toml
keystore = "/Users/.../Library/Application Support/io.parity.ethereum/chains"

[home]
account = "0x00...72"
rpc_host = "http://localhost"
rpc_port = 8545
required_confirmations = 1
password = "home_password.txt"
default_gas_price = 1_000_000_000 # 1 GWEI

[foreign]
account = "0x00...cE" 
rpc_host = "http://localhost"
rpc_port = 9545
required_confirmations = 1
gas_price_oracle_url = "https://gasprice.poa.network"
gas_price_speed = "instant"
default_gas_price = 10_000_000_000 # 10 GWEI
password = "foreign_password.txt"

[authorities]
required_signatures = 2

[transactions]
deposit_relay = { gas = 3000000 }
withdraw_relay = { gas = 3000000 }
withdraw_confirm = { gas = 3000000 }
```
